CREATE TABLE DOGOVOR (
    ID_DOGOVOR     VARCHAR(6) NOT NULL,
    DATE_DOGOVORA  DATE NOT NULL,
    NAMECARSALON   VARCHAR(15) NOT NULL,
    NAMERABOTNIC   VARCHAR(15) NOT NULL,
    COD_CUSTOMERS  VARCHAR(6) NOT NULL,
    COD_RABOTNIC   VARCHAR(6) NOT NULL,
    COD_CAR        VARCHAR(6) NOT NULL
);
ALTER TABLE DOGOVOR ADD PRIMARY KEY (ID_DOGOVOR);


