CREATE TABLE CUSTOMERS (
    ID_CUSTIMERS      VARCHAR(6) NOT NULL,
    FIRSTNAME         VARCHAR(10) NOT NULL,
    LASTNAME          VARCHAR(15) NOT NULL,
    PATRONYMIC        VARCHAR(15) NOT NULL,
    TEL_CUSTOMERS     VARCHAR(11) NOT NULL,
    ADRESS_CUSTOMERS  VARCHAR(50) NOT NULL,
    PASSPORT          VARCHAR(12) NOT NULL,
    INN               VARCHAR(20) NOT NULL
);

ALTER TABLE CUSTOMERS ADD PRIMARY KEY (ID_CUSTIMERS);

