CREATE TABLE CAR (
    ID_CAR        integer NOT NULL,
    NAMEMARKA      VARCHAR(25) NOT NULL,
    COLOR          VARCHAR(10) NOT NULL,
    KOL_VO_DVER    VARCHAR(8) NOT NULL,
    PRIVOD         VARCHAR(15) NOT NULL,
    KATEGORIYA     VARCHAR(5) NOT NULL,
    COMPLEKTAZIYA  VARCHAR(15) NOT NULL,
    CENA           integer NOT NULL,
    COD_POSTAVKI   integer NOT NULL,
    COD_KUZOVA     integer NOT NULL,
    COD_DVIG       integer NOT NULL
);
CREATE TABLE DOGOVOR (
    ID_DOGOVOR     integer NOT NULL,
    DATE_DOGOVORA  DATE NOT NULL,
    NAMECARSALON   VARCHAR(15) NOT NULL,
    NAMERABOTNIC   VARCHAR(15) NOT NULL,
    COD_CUSTOMERS  integer NOT NULL,
    COD_RABOTNIC   integer NOT NULL,
    COD_CAR        integer NOT NULL
);
CREATE TABLE DOLJNOST (
    ID_DOLJNOST    integer NOT NULL,
    NAMEDOLJ  VARCHAR(30) NOT NULL
);
CREATE TABLE CUSTOMERS (
    ID_CUSTIMERS      integer NOT NULL,
    FIRSTNAME         VARCHAR(10) NOT NULL,
    LASTNAME          VARCHAR(15) NOT NULL,
    PATRONYMIC        VARCHAR(15) NOT NULL,
    TEL_CUSTOMERS     VARCHAR(11) NOT NULL,
    ADRESS_CUSTOMERS  VARCHAR(50) NOT NULL,
    PASSPORT          VARCHAR(12) NOT NULL,
    INN               VARCHAR(20) NOT NULL
);
CREATE TABLE POSTAVKA (
    ID_POSTAVKA        integer NOT NULL,
    NAMEPROIZVOD       VARCHAR(15) NOT NULL,
    NAMEPOST   VARCHAR(15) NOT NULL,
    ADRESSPOS  VARCHAR(60) NOT NULL
);
CREATE TABLE RABOTNIC (
    ID_RABOTNIC  integer NOT NULL,
    NAMERAB      VARCHAR(15) NOT NULL,
    LASTRAB      VARCHAR(15) NOT NULL,
    TEL_RAB      VARCHAR(11) NOT NULL,
    COD_DOLZ     integer NOT NULL
);
CREATE TABLE TIP_DVIGATEL (
    ID_TIP_DVIGATEL  integer NOT NULL,
    NAME_TIP_DVIG    VARCHAR(30) NOT NULL
);
CREATE TABLE TIP_KUSOVA (
    ID_TIP_KUZOV    integer NOT NULL,
    NAME_TIP_KUZOV  VARCHAR(15) NOT NULL
);

ALTER TABLE CAR ADD PRIMARY KEY (ID_CAR);
ALTER TABLE DOGOVOR ADD PRIMARY KEY (ID_DOGOVOR);
ALTER TABLE DOLJNOST ADD PRIMARY KEY (ID_DOLJNOST);
ALTER TABLE CUSTOMERS ADD PRIMARY KEY (ID_CUSTIMERS);
ALTER TABLE POSTAVKA ADD PRIMARY KEY (ID_POSTAVKA);
ALTER TABLE RABOTNIC ADD PRIMARY KEY (ID_RABOTNIC);
ALTER TABLE TIP_DVIGATEL ADD PRIMARY KEY (ID_TIP_DVIGATEL);
ALTER TABLE TIP_KUSOVA ADD PRIMARY KEY (ID_TIP_KUZOV);


ALTER TABLE CAR ADD CONSTRAINT CAR_1 FOREIGN KEY (COD_POSTAVKI) REFERENCES POSTAVKA (ID_POSTAVKA);
ALTER TABLE CAR ADD CONSTRAINT CAR_2 FOREIGN KEY (COD_KUZOVA) REFERENCES TIP_KUSOVA (ID_TIP_KUZOV);
ALTER TABLE CAR ADD CONSTRAINT CAR_3 FOREIGN KEY (COD_DVIG) REFERENCES TIP_DVIGATEL (ID_TIP_DVIGATEL);
ALTER TABLE RABOTNIC ADD CONSTRAINT RABOTNIC_1 FOREIGN KEY (COD_DOLZ) REFERENCES DOLJNOST (ID_DOLJNOST);
ALTER TABLE DOROVOR  ADD CONSTRAINT DOROVOR_1 FOREIGN KEY (COD_RABOTNIC) REFERENCES RABOTNIC (ID_RABOTNIC);
ALTER TABLE DOROVOR  ADD CONSTRAINT DOROVOR_2 FOREIGN KEY (COD_CUSTOMERS) REFERENCES CUSTOMERS (ID_CUSTIMERS);
ALTER TABLE DOROVOR  ADD CONSTRAINT DOROVOR_3 FOREIGN KEY (COD_CAR) REFERENCES CAR (ID_CAR);
