INSERT INTO CAR VALUES (gen_id(gen_car,1), 'Mercedes-Benz E350 AT', 'Черный', '4', 'Задний', 'B', 'Базовая', 2500000, 1, 2, 2);
INSERT INTO CAR VALUES (gen_id(gen_car,1), 'Mercedes-Benz E280 AT', 'Белый', '4', 'Полный', 'B', 'Базовая', 800000, 1, 1, 2);
INSERT INTO CAR VALUES (gen_id(gen_car,1), 'Mazda 6 III (GJ)', 'Красный', '4', 'Передний', 'B', 'Базовая', 1550000, 2, 1, 2);
INSERT INTO CAR VALUES (gen_id(gen_car,1), 'Lamborghini Huracan', 'Красный', '2', 'Полный', 'B', 'Полная', 1290000, 6, 2, 2);
INSERT INTO CAR VALUES (gen_id(gen_car,1), 'Kia Soul I', 'Белый', '4', 'Передний', 'B', 'Полная', 470000, 5, 7, 2);
INSERT INTO CAR VALUES (gen_id(gen_car,1)   'Jeep Wrangler', 'Чёрный', '4', 'Полный', 'B', 'Базовая', 4380000,7, 10, 2);
INSERT INTO CAR VALUES (gen_id(gen_car,1), 'Jaguar XF II', 'Синий', '4', 'Полный', 'B', 'Полная', 2900000, 7,1, 2);
INSERT INTO CAR VALUES (gen_id(gen_car,1), 'Bugatti EB veyron', 'Оранжерый', '2', 'Полный', 'B', 'Базовый', 211000000, 3, 2, 2);
INSERT INTO CAR VALUES (gen_id(gen_car,1), 'Koenigsegg Agera', 'Серый', '2', 'Задний', 'B', 'Базовый', 9750000, 8, 2, 2);
INSERT INTO CAR VALUES (gen_id(gen_car,1), 'Skoda Octavia III', 'Серый', '4', 'Передний', 'B', 'Базовая', 1415000, 10, 9, 2);
INSERT INTO CAR VALUES (gen_id(gen_car,1), 'LADA Vesta I', 'Коричневый', '4', 'Передний', 'B', 'Базовый', 620000, 9, 1, 2);

COMMIT WORK;

