INSERT INTO DOGOVOR  VALUES (gen_id(gen_dogov,1), '2005-03-03', 'Улей', 'Рудин', 1, 10, 11);
INSERT INTO DOGOVOR  VALUES (gen_id(gen_dogov,1), '2010-12-05', 'АвтоРу', 'Денис',2, 9, 1);
INSERT INTO DOGOVOR  VALUES (gen_id(gen_dogov,1), '2006-04-12', 'АвтоРу', 'Денис', 7, 9, 2);
INSERT INTO DOGOVOR  VALUES (gen_id(gen_dogov,1), '2014-11-23', 'АвтоРу', 'Тимур', 10, 11, 4);
INSERT INTO DOGOVOR  VALUES (gen_id(gen_dogov,1), '2003-02-26', 'АвтоМосква', 'Тимур', 3, 11, 8);
INSERT INTO DOGOVOR  VALUES (gen_id(gen_dogov,1), '2004-07-06', 'АвтоСтарт', 'Тимур', 6, 11, 9);
INSERT INTO DOGOVOR  VALUES (gen_id(gen_dogov,1), '2009-09-14', 'ГрандРу', 'Рудин', 9, 10, 10);
INSERT INTO DOGOVOR  VALUES (gen_id(gen_dogov,1), '2012-12-12', 'Финиш', 'Рудин', 1, 10, 10);
INSERT INTO DOGOVOR  VALUES (gen_id(gen_dogov,1), '2005-05-16', 'АвтоМаркет', 'Денис', 5, 9, 5);
INSERT INTO DOGOVOR  VALUES (gen_id(gen_dogov,1), '2018-08-18', 'ГорячииТачки', 'Тимур', 4, 11, 7);

COMMIT WORK;
