INSERT INTO POSTAVKA  VALUES (gen_id(gen_post,1), 'Германия', 'Авто-Профи', 'г.Большаково,ул.Трудовая аллея, дом 187');
INSERT INTO POSTAVKA  VALUES (gen_id(gen_post,1), 'Япония', 'Авто-Премиум', 'г.Красногвардейск,ул.Внуково Аэропорт тер,дом 112');
INSERT INTO POSTAVKA  VALUES (gen_id(gen_post,1), 'Франция', 'Трассаэко', 'г.Крыловская,ул.Беговая 3-я,дом 68');
INSERT INTO POSTAVKA  VALUES (gen_id(gen_post,1), 'США', 'АвтоСинтез', 'г.Санкт-Петербург,ул.Международное ш,дом 6');
INSERT INTO POSTAVKA  VALUES (gen_id(gen_post,1), 'Южная Корея', 'ГрандАвто', 'г.Москва,ул. Актерский проезд,дом 191');
INSERT INTO POSTAVKA  VALUES (gen_id(gen_post,1), 'Италия', 'AlugiAvto', 'г.Москва,ул.Останкинский проезд,дом 61');
INSERT INTO POSTAVKA  VALUES (gen_id(gen_post,1), 'Британия', 'Ecako', 'г.Санкт-Петербург,ул.Новосельская,дом 105');
INSERT INTO POSTAVKA  VALUES (gen_id(gen_post,1), 'Швеция', 'OtakoMachine', 'г.Зеленоград,ул.Гришина,дом 167');
INSERT INTO POSTAVKA  VALUES (gen_id(gen_post,1), 'Россия', 'StartFar', 'г.Калининград,ул.Профсоюзная,дом 59');
INSERT INTO POSTAVKA  VALUES (gen_id(gen_post,1), 'Чехия', 'OutFast', 'г.Калининград,ул.Емельянова,дом 177');

COMMIT WORK;
