INSERT INTO DOLJNOST VALUES (gen_id(gen_dolj,1), 'Директор');
INSERT INTO DOLJNOST 
              VALUES (gen_id(gen_dolj,1), 'Заместитель Директор');
INSERT INTO DOLJNOST 
              VALUES (gen_id(gen_dolj,1), 'Юристконстультант');
INSERT INTO DOLJNOST 
              VALUES (gen_id(gen_dolj,1), 'Главный Бухгалтер');
INSERT INTO DOLJNOST
              VALUES (gen_id(gen_dolj,1), 'Помощник бухгалтера');
INSERT INTO DOLJNOST 
              VALUES (gen_id(gen_dolj,1), 'Менеджер по продажам');
INSERT INTO DOLJNOST 
              VALUES (gen_id(gen_dolj,1), 'Продавец-консультант');
INSERT INTO DOLJNOST 
              VALUES (gen_id(gen_dolj,1), 'Мерчендайзер');
INSERT INTO DOLJNOST 
              VALUES (gen_id(gen_dolj,1), 'Креативный директор');
INSERT INTO DOLJNOST
              VALUES (gen_id(gen_dolj,1), 'Менеджер по снабжению');

COMMIT WORK;
