
CREATE TABLE CAR (
    ID_CAR         VARCHAR(6) NOT NULL,
    NAMEMARKA      VARCHAR(25) NOT NULL,
    COLOR          VARCHAR(10) NOT NULL,
    KOL_VO_DVER    VARCHAR(8) NOT NULL,
    PRIVOD         VARCHAR(15) NOT NULL,
    KATEGORIYA     VARCHAR(5) NOT NULL,
    COMPLEKTAZIYA  VARCHAR(15) NOT NULL,
    CENA           VARCHAR(15) NOT NULL,
    COD_POSTAVKI   VARCHAR(6) NOT NULL,
    COD_KUZOVA     VARCHAR(6) NOT NULL,
    COD_DVIG       VARCHAR(6) NOT NULL
);
ALTER TABLE CAR ADD PRIMARY KEY (ID_CAR);

ALTER TABLE CAR ADD CONSTRAINT FK_CAR_1 FOREIGN KEY (COD_POSTAVKI) REFERENCES POSTAVKA (ID_POSTAVKA);
ALTER TABLE CAR ADD CONSTRAINT FK_CAR_2 FOREIGN KEY (COD_KUZOVA) REFERENCES TIP_KUSOVA (ID_TIP_KUZOV);
ALTER TABLE CAR ADD CONSTRAINT FK_CAR_3 FOREIGN KEY (COD_DVIG) REFERENCES TIP_DVIGATEL (ID_TIP_DVIGATEL);

