CREATE TABLE RABOTNIC (
    ID_RABOTNIC  VARCHAR(6) NOT NULL,
    NAMERAB      VARCHAR(15) NOT NULL,
    LASTRAB      VARCHAR(15) NOT NULL,
    TEL_RAB      VARCHAR(11) NOT NULL,
    COD_DOLZ     VARCHAR(5) NOT NULL
);
ALTER TABLE RABOTNIC ADD PRIMARY KEY (ID_RABOTNIC);

ALTER TABLE RABOTNIC ADD CONSTRAINT FK_RABOTNIC_1 FOREIGN KEY (COD_DOLZ) REFERENCES DOLJNOST (ID_DOLJNOST);

